### ISSUE TITLE
(htlc.js:360) SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by drandreaskrueger** [chatch/hashed-timelock-contract-ethereum#1]
```
git clone https://github.com/chatch/hashed-timelock-contract-ethereum
cd hashed-timelock-contract-ethereum/

sudo npm i -g ethereumjs-testrpc truffle
testrpc
```
then in 2nd terminal
```
truffle test
```
at first I get a `Error: Error: Exceeds block gas limit` which can be fixed easily, by inserting

    gas: 4600000, 

into truffle.js - like suggested [here](https://ethereum.stackexchange.com/a/29661).

But then this error comes up:

```
truffle test

Using network 'development'.

Compiling ./contracts/HashedTimelock.sol...
Compiling ./contracts/Migrations.sol...

Compilation warnings encountered:
[... please also consider to fix warnings thx ...]


.../chatch_hashed-timelock-contract-ethereum/test/htlc.js:360
  it("getContract() returns empty record when contract doesn't exist", async () => {
                                                                             ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:231:27
```

versions:

```
npm --version; node --version; truffle version; testrpc version | grep TestRPC
3.10.10
v6.11.4
Truffle v4.0.1 (core: 4.0.1)
Solidity v0.4.18 (solc-js)
EthereumJS TestRPC v6.0.1 (ganache-core: 2.0.0)
^C
```

**Comment by drandreaskrueger** [comment]
https://github.com/chatch/hashed-timelock-contract-ethereum/blob/master/test/htlc.js#L360-L365

**Comment by chatch** [comment]
try running with latest node.
i'm running v8.6.0 without any issues.
i guess it knows about async, arrow functions, etc. and v6 doesn't

also i'm on truffle v3 though i wouldn't expect that to be an issue here.

**Comment by drandreaskrueger** [comment]
Hah. 

Problem was on my side. Had to upgrade npm & node. Sorry. 

For anyone who encounters the same problems, this solves it:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

npm --version; node --version; truffle version; testrpc version | grep TestRPC
5.5.1
v6.11.4
Truffle v4.0.1 (core: 4.0.1)
Solidity v0.4.18 (solc-js)
EthereumJS TestRPC v6.0.1 (ganache-core: 2.0.0)
^C

```

**Comment by drandreaskrueger** [comment]
so ... sorted.

but the `Error: Error: Exceeds block gas limit` persists. 

I suggest you add that manual `gas` to your truffle.js.

see https://ethereum.stackexchange.com/a/29661

thanks

**Comment by chatch** [comment]
looks like it's a truffle 4 issue which is why i havn't seen it yet.

ok thanks.
