### ISSUE TITLE
Contract ID does not exist while calling withdraw

### ISSUE THREAD

**Issue by kirit93** [chatch/hashed-timelock-contract-ethereum#14]
I create a contract using the `newContract` method which returns the ID of the newly created contract.
This is what is returned to me ` b'}\x82\x91\xf2\x14\x89\xd6G\x8b\xbfK\xdb\xe5C@U/\x16"FYmXU\x9b\x1eX\xfc\xaf\xdc\x1a\xa2'`

I take this same bytearray and pass it to the `withdraw` function with the `preimage` and the error I get is:
```
ValueError: {'message': 'VM Exception while processing transaction: revert contractId does not exist', 'code': -32000, 'data': {'0x24acdc6c89c6e4209eca4fe4187177b4c734aca23a7a1f3a7537c391bbc1c79c': {'error': 'revert', 'program_counter': 1880, 'return': '0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000019636f6e7472616374496420646f6573206e6f7420657869737400000000000000', 'reason': 'contractId does not exist'}, 'stack': 'o: VM Exception while processing transaction: revert contractId does notexist\n    at Function.o.fromResults (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:81931)\n    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:121973\n    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:102384\n    at p (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:102041)\n    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:102094\n    at t.default (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:497368)\n   at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:103008\n    at w.n.emit (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1211583)\n    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1850382\n    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1850405\n    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:500011\n    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26124\n    at i (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:41179)\n    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:21647\n    at process.internalTickCallback (internal/process/next_tick.js:70:11)', 'name': 'o'}}
```

@chatch  Is there another way to pass in the contract id? Am I missing something here?

**Comment by chatch** [comment]
How are you unpacking the transaction receipt? Because what you should see for the contract id is a sha256 hash.

Here's how it's done in a javascript test: https://github.com/chatch/hashed-timelock-contract-ethereum/blob/master/test/htlc.js#L43

**Comment by kirit93** [comment]
I'm new to this and I'm using web3.py since I'm more comfortable with Python than JS. 

I create a contract instance as follows - 
```
contract_constructor    = contract_factory.constructor()
transaction_hash        = contract_constructor.transact(transaction_details)
transaction_receipt     = eth_provider.getTransactionReceipt(transaction_hash)
contract_address        = transaction_receipt['contractAddress']
contract_instance       = eth_provider.contract\
(
    abi                     = contract_abi,
    address                 = contract_address,
    ContractFactoryClass    = ConciseContract
)
````
**When I connect to Web3 (using my local ganache node) and try to connect to the contract deployed at "contract_address", I get an error saying InvalidAddress. Do you know why this happens?**

I create a new HTLC contract as follows -
```
contract_h  = \
contract_instance.newContract\
(
       receiver_add, 
       hashlock_bytes, 
       timelock, 
       transact    =\
       {
                'from': eth_provider.accounts[0],
                'gas': 1000000,
                'value': 9900000
        }
)
logs        = eth_provider.getTransactionReceipt(contract_h)
```

This is what I see when I print logs -
```
AttributeDict(
    {
        'transactionHash': HexBytes('0xedd3b72c70947437c249f71ce9f4ce1aaf820f9996c774426b6e10065358767f'), 
        'transactionIndex': 0, 
        'blockHash': HexBytes('0x79b48046e5d54ecbedda50862387b0d7f1e3481745af8b6e3b151cedfa7ee492'), 
        'blockNumber': 6, 'from': '0xbcfe01f4d60656d075056ca8cd7c1e454fdf8d13', 
        'to': '0x011d1ec04d191d1a29f62d25995729d3229578a5', 
        'gasUsed': 147096, 
        'cumulativeGasUsed': 147096, 
        'contractAddress': None, 
        'logs': [
            AttributeDict(
                {
                    'logIndex': 0, 
                    'transactionIndex': 0, 
                    'transactionHash': HexBytes('0xedd3b72c70947437c249f71ce9f4ce1aaf820f9996c774426b6e10065358767f'), 
                    'blockHash': HexBytes('0x79b48046e5d54ecbedda50862387b0d7f1e3481745af8b6e3b151cedfa7ee492'), 
                    'blockNumber': 6, 
                    'address': '0x011d1eC04d191D1A29F62D25995729D3229578a5', 
                    'data': '0x0000000000000000000000000000000000000000000000000000000000970fe05714f358b6aa87565ec6c1caee436fda9e4d483e4ef32ee15d5ecde9586d4e92000000000000000000000000000000000000000000000000000000005cef2a3b', 
                    'topics': [
                        HexBytes('0x329a8316ed9c3b2299597538371c2944c5026574e803b1ec31d6113e1cd67bde'), 
                        HexBytes('0xa7868b75dc1dcd67f8562c9d6e69bbc5af02c585b226c714bc01a0267ac553d0'), 
                        HexBytes('0x000000000000000000000000bcfe01f4d60656d075056ca8cd7c1e454fdf8d13'), 
                        HexBytes('0x000000000000000000000000ec084b299923ec193571d48991315c55b0e58a74')
                    ], 
                    'type': 'mined'
                }
            )
        ], 
        'status': 1, 
        'logsBloom': HexBytes('0x00000000000000000000000000000000400000000000000080000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000010000000000000000000000000000000000000002000002200000000000000000000000000000000000000000000000002000000000001000800000000000000000000000000000000000004000000000400000000000000000000000000000000000000000004000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000'), 
        'v': '0x1b', 
        'r': '0xaa883903b3c64f03675020157f696deed85711b0cd732f0122d5cf9287b90891', 
        's': '0x16eafe1c02a0b8ceeff7b59ad87d7fa520c6814dc3cc63d1ed6cdfd88e109dd8'
    }
)
```

The address of the contract is `None` and the logs don't have the `contractID` in them. **Am I missing something here?**

My last question is - while trying this on Remix, I'm confused about how to pass the preimage to the `withdraw` function. When I pass in the hex value of my string, I receive an error because the hashes do not match.
In the `hashlockMatches` function - is it the hex value of the string that is hashed, is it the string (bytes) itself that is hashed?
eg. if my preimage is `'abc'`, the `sha256` hash is `0xba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad`. This hash is what I pass to `newContract`. In withdraw what should be passed? 
1. `'abc'` results in - `Error: invalid bytes32 value (arg="", type="string", value="abc")`
2. If I convert it to bytes and pass in `'\\x61\\x62\\x63'` I see - `Error: invalid bytes32 value (arg="", type="string", value="'\\x61\\x62\\x63'"`
3. If I pass in the hex value `0x3d3e3f` I see - `transact to HashedTimelock.withdraw errored: VM Exception while processing transaction: revert hashlock hash does not match `.

I'm not sure what to do. Could you please provide some details on how I can solve these issues? Your help is deeply appreciated. Thank you.

**Comment by kirit93** [comment]
@chatch I was able to solve the issues and I can successfully call the withdraw functions. This helped me out - https://github.com/ethereum/web3.py/issues/429

Secret - `b'\xbe*\\\x9b\x90aa~\xcbTV\xd6\xdb\x10\x85)E?OVJ\xde=\xb4\x8e\xa2\\ie\xa5b\xb5'`
Hex Secret - `0xbe2a5c9b9061617ecb5456d6db108529453f4f564ade3db48ea25c6965a562b5`
Hashlock - `0xbf20662fa58163a7d0d58da7005b593886a6029f620519f80c9d4260487e59d0`

When I call `getContract` I see the last parameter as the preimage for my hashlock. 
```
['0xE7058746A77D559DeE9964898889B340c619313e',
 '0x3a11ACE581A8686b77f69b043Ad7BDF14B94D26d',
 2000000000000000000,
 b'\x82\x16\x81+\xf4U\x1a\xae\xc4\xa2\x1a\x0c.\xc0\xf3\x8d\xa5\xb6I\x8a\x90\xa7M\x85\xe4\xeb\x0f\x02\x0f\xf6\xee\xd6',
 1559102189,
 True,
 False,
 b'X\x89\x8a\xb1f\x1f\xeeC+\x81\xeb\x96L\x1d\xdf\xd20\xf7\xc2|\xa3\t\xa42\xe1\xffbBw\tb\xf0']
```

How do I decode the preimage such that it matches what I started with?

**Comment by chatch** [comment]
sorry for the late reply. did you decode the preimage? i don't what that format is but presumably web.py is encoding all bytes32 / bytes variables in this way?

**Comment by chatch** [comment]
@kirit93 did this get solved in the end? closing this for now as I believe it was a web.py issue.
