### ISSUE TITLE
Using ropsten testnet 2 passing 9 failing

### ISSUE THREAD

**Issue by Fy45** [chatch/hashed-timelock-contract-ethereum#15]
Hi
I've adjusted the htlc.js test file and truffle configuration according to my account set up and to run it with the command
`truffle test test/htlc.js --network ropsten` and got these errors:
```  
Contract: HashedTimelock
    ✓ newContract() should create new contract and store correct details (61335ms)
    1) newContract() should fail when no ETH sent

    Events emitted during test:
    ---------------------------

    Transfer(from: <indexed> 0xB618C2730C203C23a5A8781E8114e4f5B28D5243 (address), to: <indexed> 0x2251d101026A120eB8ee8367191834FE1F31be02 (address), value: 1000000000000000000 (uint256))
    LogHTLCNew(contractId: <indexed> 0x75e3dad7c3d7a0885cc92da127a75d81051420a7c4d12bba0720b3f468a915f4 (bytes32), sender: <indexed> 0xe2B1B5d92b64846D815cd34c674973f88DcefF4d (address), receiver: <indexed> 0x209f4b189e246Ae171da5a6F1815c91C70CAA23A (address), amount: 1000000000000000 (uint256), hashlock: 0x47c28c2c6728b718d38021d5c624f106da8a3b3c14351dce3bc7012427779a9b (bytes32), timelock: 1563971231 (uint256))
.......
    ✓ getContract() returns empty record when contract doesn't exist (1146ms)


  2 passing (6m)
  9 failing

  1) Contract: HashedTimelock
       newContract() should fail when no ETH sent:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at isTrue (test/htlc.js:92:14)
      at tryCatch (node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as throw] (node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (test/htlc.js:11:103)
      at _throw (test/htlc.js:13:291)
      at process._tickCallback (internal/process/next_tick.js:68:7)
......

  3) Contract: HashedTimelock
       newContract() should reject a duplicate contract request:
     Error: Transaction: 0xfdc7410a964b5d3f851715d59edb16ad4d84f426a15c0ef5e7cd090222c38b48 exited with an error (status 0). 
     Please check that the transaction:
     - satisfies all conditions set by Solidity `require` statements.
     - does not trigger a Solidity `revert` statement.


```
the LogHTLCNew event keeps the right information but I don't get the idea of `Transfer` in this scenario, how come the first one passed but remaining has the error output...

To be honest I've stuck here for 2 days and sincerely don't know why. Am I interacting with the contract in the wrong way?
Hope you could take a look and supervised me a little...
Thanks so much

My truffle version output:
Truffle v5.0.28 (core: 5.0.28)
Solidity v0.5.8 (solc-js)
Node v10.13.0
Web3.js v1.0.0-beta.37

**Comment by chatch** [comment]
hi @Fy45 this may be related to you using a more recent version of truffle. try the version we are using in package.json and see if it works with that one.

**Comment by Fy45** [comment]
Thanks for the explanation! Will try it later

**Comment by chatch** [comment]
any luck with this with the later version of truffle?
the project truffle config has changed quite a bit since this issue so may be worth trying again.
see travis tests are working fine with ganache and truffle now.
closing for now but open it again if you still have the issue.
