### ISSUE TITLE
7 tests failing

### ISSUE THREAD

**Issue by drandreaskrueger** [chatch/hashed-timelock-contract-ethereum#2]
I get a

>  4 passing (3s)
>  7 failing

when I do:
```
testrpc
truffle test
```

**Comment by drandreaskrueger** [comment]
Details:

```

  4 passing (3s)
  7 failing

  1) Contract: HashedTimelock newContract() should fail when no ETH sent:
     Uncaught AssertionError: expected 'VM Exception while processing transaction: revert' to equal 'VM Exception while processing transaction: invalid opcode'
      at HashedTimelock.deployed.then.then.catch.err (test/htlc.js:107:16)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) Contract: HashedTimelock newContract() should fail with timelocks in the past:
     Uncaught AssertionError: expected 'VM Exception while processing transaction: revert' to equal 'VM Exception while processing transaction: invalid opcode'
      at HashedTimelock.deployed.then.then.catch.err (test/htlc.js:124:16)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  3) Contract: HashedTimelock newContract() should reject a duplicate contract request:
     Uncaught AssertionError: expected 'VM Exception while processing transaction: revert' to equal 'VM Exception while processing transaction: invalid opcode'
      at htlc.newContract.then.then.catch.err (test/htlc.js:146:18)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  4) Contract: HashedTimelock withdraw() should fail if preimage does not hash to hashX:
     Uncaught AssertionError: expected 'VM Exception while processing transaction: revert' to equal 'VM Exception while processing transaction: invalid opcode'
      at htlc.withdraw.then.catch.err (test/htlc.js:208:22)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  5) Contract: HashedTimelock withdraw() should fail if caller is not the receiver :
     Uncaught AssertionError: expected 'VM Exception while processing transaction: revert' to equal 'VM Exception while processing transaction: invalid opcode'
      at htlc.withdraw.then.catch.err (test/htlc.js:230:22)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  6) Contract: HashedTimelock withdraw() should fail after timelock expiry:
     Uncaught Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /usr/lib/node_modules/truffle/build/cli.bundled.js:331156:36
      at /usr/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  7) Contract: HashedTimelock refund() should fail before the timelock expiry:
     Uncaught AssertionError: expected 'VM Exception while processing transaction: revert' to equal 'VM Exception while processing transaction: invalid opcode'
      at htlc.refund.then.catch.err (test/htlc.js:353:22)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)


```

versions:

```
npm --version; node --version; truffle version; testrpc version | grep TestRPC
5.5.1
v9.0.0
Truffle v4.0.1 (core: 4.0.1)
Solidity v0.4.18 (solc-js)
EthereumJS TestRPC v6.0.1 (ganache-core: 2.0.0)
^C
```

**Comment by chatch** [comment]
because REVERT is now an opcode in the EVM (ethereumjs-testrpc v6).

**Comment by drandreaskrueger** [comment]
easy to fix?

**Comment by chatch** [comment]
well it's just returning a different string message depending on what version of the evm your running.

so now you can just run the older version of ethereumjs-testrpc and the tests will pass.

but later on the fix would be to retest everything with latest EVM and then update the expected messages in the test.

**Comment by chatch** [comment]
all tests pass now - contracts, truffle, etc. were all updated a couple of weeks back which fixes this issue

**Comment by drandreaskrueger** [comment]
perfect, thanks
