### ISSUE TITLE
7 not 8 return values

### ISSUE THREAD

**Issue by drandreaskrueger** [chatch/hashed-timelock-contract-ethereum#5]
TODO: With new solidity code, update json and deploy new contracts onto both chains.

Now, only when I deployed the contracts myself, I could get them working.

Long story: 

*sigh*, I have just spent 3 hours banging my head against the wall, what prevented `getContract(contractId)` to be working with Web3.py. First there were strange types returned, then strange error message. I am new to Web3.py, and Web3.py itself is quite new too - so I expected the problem on either my side, or with Web3.py.

Turns out (at least one of) your [deployed contracts](https://github.com/chatch/hashed-timelock-contract-ethereum/blob/ed00c58b5346bcf78810e82cfc97546445a4588d/README.md#hashed-timelock-contract-ethereum) simply returned 7 not 8 values when getContract(contractId) is called. And Web3.py did not like that, because the ABI said 8. No wonder I could not get it working.

Had you perhaps deployed an older version of your solidity code on those 2 addresses?  
Or were the HashedTimelock.sol and HashedTimelock.json not in sync?

Actually, originally I had been very thankful you had readily deployed contracts on Ropsten and Rinkeby - "great service" - because I had hoped that would save me time. 

But regardless, great work!  This repo is much appreciated.

**Comment by drandreaskrueger** [comment]
(for other users with the same problem I am leaving the error message here, so google can index it)

```
Traceback (most recent call last):
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/web3/contract.py", line 842, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/eth_abi/abi.py", line 109, in decode_abi
    return decoder(stream)
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/eth_abi/decoding.py", line 102, in __call__
    return self.decode(stream)
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/eth_utils/functional.py", line 33, in inner
    return callback(fn(*args, **kwargs))
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/eth_abi/decoding.py", line 140, in decode
    yield decoder(stream)
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/eth_abi/decoding.py", line 102, in __call__
    return self.decode(stream)
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/eth_abi/decoding.py", line 165, in decode
    raw_data = cls.read_data_from_stream(stream)
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/eth_abi/decoding.py", line 247, in read_data_from_stream
    len(data),

eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...//hashed-time-lock-contract/src/foobar.py", line 71, in <module>
    answer = C.getContract(contractId)
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/web3/contract.py", line 803, in __call__
    return self.__prepared_function(**kwargs)(*args)
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/web3/contract.py", line 864, in call_contract_function
    raise_from(BadFunctionCallOutput(msg), e)
  File "...//hashed-time-lock-contract/env/lib/python3.5/site-packages/web3/utils/exception_py3.py", line 2, in raise_from
    raise my_exception from other_exception
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call getContract return data

 0x00000000000000000000000025f579697ce3fe1cf122fc5ffae9f1d83f16c676000000000000000000000000c62d9f5092737fa7689579e279a3a1dd5543fb9e00000000000000000000000000000000000000000000000000038d7ea4c68000c37133153bd6d7669e77ab3a8bebf9d04bd3b3b4aeaff030729b4a53486c95f0000000000000000000000000000000000000000000000000000000005a14334d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

 for output_types ['address', 'address', 'uint256', 'bytes32', 'uint256', 'bool', 'bool', 'bytes32']
```

when trying to read (constant) '.getContract(contractId)'  
https://github.com/chatch/hashed-timelock-contract-ethereum/blob/1adc535ac5d63e74c64a8deabf8eb26afb774e42/contracts/HashedTimelock.sol#L167-L185  

and that `0x00000000000000000000000025f579697ce3fe1cf...` return data is 450 hex letters incl 0x, i.e. 448 / 2 / 32 = 7 words not 8.

**Comment by drandreaskrueger** [comment]
But for avoidance of doubt: My problem's solved, by deploying the smart contract myself. 

Thanks a million!

**Comment by chatch** [comment]
this was due to the deployed testnet contract not matching the repo head hey?

it's still the case. i'll deploy to kovan and ropsten sometime soon.

**Comment by chatch** [comment]
closing - new contract deployed to testnets
