### ISSUE TITLE
htlc.js: Syntax error

### ISSUE THREAD

**Issue by danmuf** [chatch/hashed-timelock-contract-ethereum#7]
If I try to run htlc.js, I get the following error message:

(function (exports, require, module, __filename, __dirname) { import Promise from 'bluebird'
                                                                     ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)

node version 10.3.0

Do you have any idea why it fails?

**Comment by danmuf** [comment]
And it never created a /build directory...

**Comment by chatch** [comment]
hi danmif, htlc.js is a truffle test, see here: http://truffleframework.com/docs/getting_started/javascript-tests  so you can't execute it directly with node.

install truffle and run the test with "npm run test" or "truffle test".

**Comment by danmuf** [comment]
Thanks @chatch!
